baseURL: 'https://johanngerberding.github.io/'
languageCode: 'en-us'
title: 'Johanns Blog'
theme: 'hugo-PaperMod'
enableEmoji: true
math: true

params:
  defaultTheme: dark
  homeInfoParams: 
    Title: Hi there!
    Content: My name is Johann and this is my blog where I sometimes post about stuff that interests me or things that I've learned.
  
  socialIcons:
    - name: linkedin
      url: 'https://www.linkedin.com/in/johann-gerberding-a23a31225/'
    - name: github
      url: 'https://github.com/johanngerberding'
    - name: researchgate
      url: 'https://www.researchgate.net/profile/Johann-Gerberding'
    - name: xing
      url: 'https://www.xing.com/profile/Johann_Gerberding/cv'
      
  mainSections: ["posts"]
  ShowReadingTime: true

menu:
  main:
  - identifier: posts
    name: posts
    params:
      class: highlight-menu-item
    pre: <i class='fa fa-heart'></i>
    url: /posts/
    weight: 2

  - identifier: about-me
    name: about
    params:
      class: highlight-menu-item
    pre: <i class='fa fa-heart'></i>
    url: /about-me/
    weight: 1
  
markup.goldmark.renderer:
  unsafe: true